import React from "react";
import Footer from "@/components/layouts/footer";
import Header from "@/components/layouts/header";
// import type {Metadata} from "next";
import {CartProvider} from "@/contexts/cart-context";

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayoutPage({
                                           children,
                                       }: Readonly<{ children: React.ReactNode }>) {
    return (
        <main className="w-full min-h-screen flex flex-col">
            <CartProvider>
                <Header/>
                <main
                    className="flex-grow mb-5 mt-10 px-8 overflow-y-auto overflow-x-hidden flex items-center justify-center h-fit">
                    {children}
                </main>
                <Footer/>
            </CartProvider>
        </main>

    );
}
